// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/def.proto

package itemstore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The Item message corresponds to the Item struct in your Go code.
type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field numbers (1, 2, 3) are unique identifiers for the fields in the binary encoding.
	Id            int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_def_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_def_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_def_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// The request message for the InsertItem RPC.
// It contains the data needed to create a new item.
type InsertItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertItemRequest) Reset() {
	*x = InsertItemRequest{}
	mi := &file_proto_def_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertItemRequest) ProtoMessage() {}

func (x *InsertItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_def_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertItemRequest.ProtoReflect.Descriptor instead.
func (*InsertItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_def_proto_rawDescGZIP(), []int{1}
}

func (x *InsertItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InsertItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// The response message for the InsertItem RPC.
// It's empty because success is indicated by a gRPC OK status.
// An error from the Go function would be translated into a gRPC error status.
type InsertItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertItemResponse) Reset() {
	*x = InsertItemResponse{}
	mi := &file_proto_def_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertItemResponse) ProtoMessage() {}

func (x *InsertItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_def_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertItemResponse.ProtoReflect.Descriptor instead.
func (*InsertItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_def_proto_rawDescGZIP(), []int{2}
}

// The request message for the GetItems RPC.
// It's empty because this RPC retrieves all items and requires no input parameters.
type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_proto_def_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_def_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_def_proto_rawDescGZIP(), []int{3}
}

// The response message for the GetItems RPC.
// It contains a list of Item messages. The 'repeated' keyword indicates
// that this field can appear zero or more times (like a slice or array).
type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_proto_def_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_def_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_def_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_def_proto protoreflect.FileDescriptor

const file_proto_def_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/def.proto\x12\titemstore\"L\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"I\n" +
	"\x11InsertItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x14\n" +
	"\x12InsertItemResponse\"\x11\n" +
	"\x0fGetItemsRequest\"9\n" +
	"\x10GetItemsResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.itemstore.ItemR\x05items2\xa3\x01\n" +
	"\vItemService\x12M\n" +
	"\n" +
	"InsertItem\x12\x1c.itemstore.InsertItemRequest\x1a\x1d.itemstore.InsertItemResponse\"\x00(\x01\x12E\n" +
	"\bGetItems\x12\x1a.itemstore.GetItemsRequest\x1a\x1b.itemstore.GetItemsResponse\"\x00B\x18Z\x16your-project/itemstoreb\x06proto3"

var (
	file_proto_def_proto_rawDescOnce sync.Once
	file_proto_def_proto_rawDescData []byte
)

func file_proto_def_proto_rawDescGZIP() []byte {
	file_proto_def_proto_rawDescOnce.Do(func() {
		file_proto_def_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_def_proto_rawDesc), len(file_proto_def_proto_rawDesc)))
	})
	return file_proto_def_proto_rawDescData
}

var file_proto_def_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_def_proto_goTypes = []any{
	(*Item)(nil),               // 0: itemstore.Item
	(*InsertItemRequest)(nil),  // 1: itemstore.InsertItemRequest
	(*InsertItemResponse)(nil), // 2: itemstore.InsertItemResponse
	(*GetItemsRequest)(nil),    // 3: itemstore.GetItemsRequest
	(*GetItemsResponse)(nil),   // 4: itemstore.GetItemsResponse
}
var file_proto_def_proto_depIdxs = []int32{
	0, // 0: itemstore.GetItemsResponse.items:type_name -> itemstore.Item
	1, // 1: itemstore.ItemService.InsertItem:input_type -> itemstore.InsertItemRequest
	3, // 2: itemstore.ItemService.GetItems:input_type -> itemstore.GetItemsRequest
	2, // 3: itemstore.ItemService.InsertItem:output_type -> itemstore.InsertItemResponse
	4, // 4: itemstore.ItemService.GetItems:output_type -> itemstore.GetItemsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_def_proto_init() }
func file_proto_def_proto_init() {
	if File_proto_def_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_def_proto_rawDesc), len(file_proto_def_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_def_proto_goTypes,
		DependencyIndexes: file_proto_def_proto_depIdxs,
		MessageInfos:      file_proto_def_proto_msgTypes,
	}.Build()
	File_proto_def_proto = out.File
	file_proto_def_proto_goTypes = nil
	file_proto_def_proto_depIdxs = nil
}
